analyzer_rules:
  - all

opt_in_rules:
  - all

disabled_rules:
  - contrasted_opening_brace
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - nesting
  - no_empty_block
  - sorted_enum_cases
  - trailing_closure
