analyzer_rules:
  - all

opt_in_rules:
  - all

disabled_rules:
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - discouraged_default_parameter
  - explicit_acl
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - no_magic_numbers
  - sorted_enum_cases
  - switch_case_on_newline
  - trailing_closure
  - type_contents_order
  - vertical_whitespace_between_cases

indentation_width:
  include_multiline_strings: false

nesting:
  type_level: 2

no_empty_block:
  disabled_block_types: [initializer_bodies]

opening_brace:
  ignore_multiline_statement_conditions: true
