analyzer_rules:
  - all

opt_in_rules:
  - all

disabled_rules:
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - nesting
  - no_empty_block
  - no_magic_numbers
  - sorted_enum_cases
  - switch_case_on_newline
  - trailing_closure
  - type_contents_order
  - vertical_whitespace_between_cases
